//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Lab2Grammar.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="Lab2GrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ILab2GrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="Lab2GrammarParser.unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnit([NotNull] Lab2GrammarParser.UnitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Dec</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDec([NotNull] Lab2GrammarParser.DecContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Mod</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMod([NotNull] Lab2GrammarParser.ModContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Brackets</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBrackets([NotNull] Lab2GrammarParser.BracketsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AdditionOrSubtraction</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditionOrSubtraction([NotNull] Lab2GrammarParser.AdditionOrSubtractionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Num</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum([NotNull] Lab2GrammarParser.NumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MultiplicationOrDivision</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicationOrDivision([NotNull] Lab2GrammarParser.MultiplicationOrDivisionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CellRef</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCellRef([NotNull] Lab2GrammarParser.CellRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Power</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPower([NotNull] Lab2GrammarParser.PowerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NegNum</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegNum([NotNull] Lab2GrammarParser.NegNumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Inc</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInc([NotNull] Lab2GrammarParser.IncContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Invalid</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInvalid([NotNull] Lab2GrammarParser.InvalidContext context);
}
