//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Lab2Grammar.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class Lab2GrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		LBRACKET=1, RBRACKET=2, CELLREF=3, POWER=4, MULTIPLICATION=5, INC=6, DEC=7, 
		DIV=8, ADDITION=9, SUBTRACTION=10, MOD=11, NUM=12, WHITESPACE=13, INVALID=14;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"LBRACKET", "RBRACKET", "CELLREF", "POWER", "MULTIPLICATION", "INC", "DEC", 
		"DIV", "ADDITION", "SUBTRACTION", "MOD", "NUM", "WHITESPACE", "INVALID"
	};


	public Lab2GrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public Lab2GrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", null, "'^'", "'*'", "'inc'", "'dec'", "'/'", "'+'", 
		"'-'", "' mod '"
	};
	private static readonly string[] _SymbolicNames = {
		null, "LBRACKET", "RBRACKET", "CELLREF", "POWER", "MULTIPLICATION", "INC", 
		"DEC", "DIV", "ADDITION", "SUBTRACTION", "MOD", "NUM", "WHITESPACE", "INVALID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Lab2Grammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static Lab2GrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x10', 'P', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x6', '\x4', '%', '\n', '\x4', '\r', 
		'\x4', '\xE', '\x4', '&', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\r', '\x6', '\r', '\x44', '\n', '\r', '\r', '\r', '\xE', 
		'\r', '\x45', '\x3', '\xE', '\x6', '\xE', 'I', '\n', '\xE', '\r', '\xE', 
		'\xE', '\xE', 'J', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x2', '\x2', '\x10', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', 
		'\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', 
		'\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x3', 
		'\x2', '\x3', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x2', 'R', '\x2', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x5', '!', '\x3', '\x2', 
		'\x2', '\x2', '\a', '$', '\x3', '\x2', '\x2', '\x2', '\t', '*', '\x3', 
		'\x2', '\x2', '\x2', '\v', ',', '\x3', '\x2', '\x2', '\x2', '\r', '.', 
		'\x3', '\x2', '\x2', '\x2', '\xF', '\x32', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\x36', '\x3', '\x2', '\x2', '\x2', '\x13', '\x38', '\x3', '\x2', 
		'\x2', '\x2', '\x15', ':', '\x3', '\x2', '\x2', '\x2', '\x17', '<', '\x3', 
		'\x2', '\x2', '\x2', '\x19', '\x43', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'H', '\x3', '\x2', '\x2', '\x2', '\x1D', 'N', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', ' ', '\a', '*', '\x2', '\x2', ' ', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '!', '\"', '\a', '+', '\x2', '\x2', '\"', '\x6', '\x3', '\x2', 
		'\x2', '\x2', '#', '%', '\x4', '\x43', '\\', '\x2', '$', '#', '\x3', '\x2', 
		'\x2', '\x2', '%', '&', '\x3', '\x2', '\x2', '\x2', '&', '$', '\x3', '\x2', 
		'\x2', '\x2', '&', '\'', '\x3', '\x2', '\x2', '\x2', '\'', '(', '\x3', 
		'\x2', '\x2', '\x2', '(', ')', '\x5', '\x19', '\r', '\x2', ')', '\b', 
		'\x3', '\x2', '\x2', '\x2', '*', '+', '\a', '`', '\x2', '\x2', '+', '\n', 
		'\x3', '\x2', '\x2', '\x2', ',', '-', '\a', ',', '\x2', '\x2', '-', '\f', 
		'\x3', '\x2', '\x2', '\x2', '.', '/', '\a', 'k', '\x2', '\x2', '/', '\x30', 
		'\a', 'p', '\x2', '\x2', '\x30', '\x31', '\a', '\x65', '\x2', '\x2', '\x31', 
		'\xE', '\x3', '\x2', '\x2', '\x2', '\x32', '\x33', '\a', '\x66', '\x2', 
		'\x2', '\x33', '\x34', '\a', 'g', '\x2', '\x2', '\x34', '\x35', '\a', 
		'\x65', '\x2', '\x2', '\x35', '\x10', '\x3', '\x2', '\x2', '\x2', '\x36', 
		'\x37', '\a', '\x31', '\x2', '\x2', '\x37', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '\x38', '\x39', '\a', '-', '\x2', '\x2', '\x39', '\x14', '\x3', 
		'\x2', '\x2', '\x2', ':', ';', '\a', '/', '\x2', '\x2', ';', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '<', '=', '\a', '\"', '\x2', '\x2', '=', '>', '\a', 
		'o', '\x2', '\x2', '>', '?', '\a', 'q', '\x2', '\x2', '?', '@', '\a', 
		'\x66', '\x2', '\x2', '@', '\x41', '\a', '\"', '\x2', '\x2', '\x41', '\x18', 
		'\x3', '\x2', '\x2', '\x2', '\x42', '\x44', '\x4', '\x32', ';', '\x2', 
		'\x43', '\x42', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\x3', '\x2', 
		'\x2', '\x2', '\x45', '\x43', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', 
		'\x3', '\x2', '\x2', '\x2', '\x46', '\x1A', '\x3', '\x2', '\x2', '\x2', 
		'G', 'I', '\t', '\x2', '\x2', '\x2', 'H', 'G', '\x3', '\x2', '\x2', '\x2', 
		'I', 'J', '\x3', '\x2', '\x2', '\x2', 'J', 'H', '\x3', '\x2', '\x2', '\x2', 
		'J', 'K', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\x3', '\x2', '\x2', '\x2', 
		'L', 'M', '\b', '\xE', '\x2', '\x2', 'M', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', 'N', 'O', '\v', '\x2', '\x2', '\x2', 'O', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', '\x6', '\x2', '&', '\x45', 'J', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
