//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Lab2Grammar.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="Lab2GrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ILab2GrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Lab2GrammarParser.unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnit([NotNull] Lab2GrammarParser.UnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Lab2GrammarParser.unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnit([NotNull] Lab2GrammarParser.UnitContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Dec</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDec([NotNull] Lab2GrammarParser.DecContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Dec</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDec([NotNull] Lab2GrammarParser.DecContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Mod</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMod([NotNull] Lab2GrammarParser.ModContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Mod</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMod([NotNull] Lab2GrammarParser.ModContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Brackets</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBrackets([NotNull] Lab2GrammarParser.BracketsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Brackets</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBrackets([NotNull] Lab2GrammarParser.BracketsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AdditionOrSubtraction</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditionOrSubtraction([NotNull] Lab2GrammarParser.AdditionOrSubtractionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AdditionOrSubtraction</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditionOrSubtraction([NotNull] Lab2GrammarParser.AdditionOrSubtractionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Num</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum([NotNull] Lab2GrammarParser.NumContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Num</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum([NotNull] Lab2GrammarParser.NumContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MultiplicationOrDivision</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicationOrDivision([NotNull] Lab2GrammarParser.MultiplicationOrDivisionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MultiplicationOrDivision</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicationOrDivision([NotNull] Lab2GrammarParser.MultiplicationOrDivisionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CellRef</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCellRef([NotNull] Lab2GrammarParser.CellRefContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CellRef</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCellRef([NotNull] Lab2GrammarParser.CellRefContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Power</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPower([NotNull] Lab2GrammarParser.PowerContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Power</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPower([NotNull] Lab2GrammarParser.PowerContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NegNum</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegNum([NotNull] Lab2GrammarParser.NegNumContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NegNum</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegNum([NotNull] Lab2GrammarParser.NegNumContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Inc</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInc([NotNull] Lab2GrammarParser.IncContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Inc</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInc([NotNull] Lab2GrammarParser.IncContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Invalid</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInvalid([NotNull] Lab2GrammarParser.InvalidContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Invalid</c>
	/// labeled alternative in <see cref="Lab2GrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInvalid([NotNull] Lab2GrammarParser.InvalidContext context);
}
